const std = @import("std");
const zcc = @import("compile_commands");

pub fn build(b: *std.Build) void {
    // make a list of targets that have include files and c source files
    var targets = std.ArrayList(*std.Build.Step.Compile).init(b.allocator);

    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const exe = b.addExecutable(.{
        .name = "hello",
        .target = target,
        .optimize = optimize,
    });
    b.installArtifact(exe);
    targets.append(exe) catch @panic("OOM");

    exe.addCSourceFiles(
        .{
            .files = &.{
                "hello.cpp",
            },
        },
    );
    exe.addCSourceFiles(.{
        .root = b.path("source"),
        .files = &.{
            "platform/ansiwrit.cpp",
            "platform/base64.cpp",
            "platform/codepage.cpp",
            "platform/colors.cpp",
            "platform/conctl.cpp",
            "platform/dir.cpp",
            "platform/dispbuff.cpp",
            "platform/errredir.cpp",
            "platform/events.cpp",
            "platform/far2l.cpp",
            "platform/findfrst.cpp",
            // "platform/gpminput.cpp",
            "platform/hardware.cpp",
            // "platform/linuxcon.cpp",
            "platform/mutex.cpp",
            // "platform/ncurdisp.cpp",
            // "platform/ncursinp.cpp",
            "platform/platfcon.cpp",
            "platform/platform.cpp",
            "platform/sighandl.cpp",
            // "platform/sigwinch.cpp",
            "platform/strings.cpp",
            "platform/termdisp.cpp",
            "platform/termio.cpp",
            "platform/ttext.cpp",
            // "platform/unixclip.cpp",
            // "platform/unixcon.cpp",
            "platform/utf8.cpp",
            "platform/win32con.cpp",
            "platform/windows.cpp",
            "platform/winwidth.cpp",
            "tvision/colorsel.cpp",
            "tvision/drivers.cpp",
            "tvision/drivers2.cpp",
            "tvision/edits.cpp",
            "tvision/editstat.cpp",
            "tvision/fmtstr.cpp",
            "tvision/framelin.cpp",
            // "tvision/geninc.cpp",
            "tvision/grp.cpp",
            "tvision/hardwrvr.cpp",
            "tvision/help.cpp",
            "tvision/helpbase.cpp",
            "tvision/histlist.cpp",
            "tvision/mapcolor.cpp",
            "tvision/menu.cpp",
            "tvision/misc.cpp",
            "tvision/msgbox.cpp",
            "tvision/new.cpp",
            "tvision/newstr.cpp",
            "tvision/nmbkgrnd.cpp",
            "tvision/nmbutton.cpp",
            "tvision/nmchdrdl.cpp",
            "tvision/nmchkbox.cpp",
            "tvision/nmclrsel.cpp",
            "tvision/nmclustr.cpp",
            "tvision/nmcollct.cpp",
            "tvision/nmdialog.cpp",
            "tvision/nmdirbox.cpp",
            "tvision/nmdircol.cpp",
            "tvision/nmdsktop.cpp",
            "tvision/nmeditor.cpp",
            "tvision/nmfilcol.cpp",
            "tvision/nmfildlg.cpp",
            "tvision/nmfillst.cpp",
            "tvision/nmframe.cpp",
            "tvision/nmgroup.cpp",
            "tvision/nmhist.cpp",
            "tvision/nminptln.cpp",
            "tvision/nmlabel.cpp",
            "tvision/nmlstbox.cpp",
            "tvision/nmlstvwr.cpp",
            "tvision/nmmnubar.cpp",
            "tvision/nmmnubox.cpp",
            "tvision/nmmnupop.cpp",
            "tvision/nmmnuvw.cpp",
            "tvision/nmmulchk.cpp",
            "tvision/nmoutlin.cpp",
            "tvision/nmprmtxt.cpp",
            "tvision/nmrbtns.cpp",
            "tvision/nmrescol.cpp",
            "tvision/nmscoll.cpp",
            "tvision/nmscrbar.cpp",
            "tvision/nmscroll.cpp",
            "tvision/nmstctxt.cpp",
            "tvision/nmstddlg.cpp",
            "tvision/nmstline.cpp",
            "tvision/nmstrcol.cpp",
            "tvision/nmstrlst.cpp",
            "tvision/nmvalida.cpp",
            "tvision/nmview.cpp",
            "tvision/nmwindow.cpp",
            "tvision/palette.cpp",
            "tvision/popupmnu.cpp",
            "tvision/prntcnst.cpp",
            "tvision/sbkgrnd.cpp",
            "tvision/sbutton.cpp",
            "tvision/schdrdlg.cpp",
            "tvision/scheckbo.cpp",
            "tvision/sclrsel.cpp",
            "tvision/scluster.cpp",
            "tvision/sdesktop.cpp",
            "tvision/sdialog.cpp",
            "tvision/sdircoll.cpp",
            "tvision/sdirlist.cpp",
            "tvision/seditors.cpp",
            "tvision/sfilcoll.cpp",
            "tvision/sfildlg.cpp",
            "tvision/sfilelst.cpp",
            "tvision/sfinfpne.cpp",
            "tvision/sfinputl.cpp",
            "tvision/sframe.cpp",
            "tvision/sgroup.cpp",
            "tvision/shistory.cpp",
            "tvision/sinputli.cpp",
            "tvision/slabel.cpp",
            "tvision/slistbox.cpp",
            "tvision/slstview.cpp",
            "tvision/smenubar.cpp",
            "tvision/smenubox.cpp",
            "tvision/smenupop.cpp",
            "tvision/smnuview.cpp",
            "tvision/smulchkb.cpp",
            "tvision/snprintf.cpp",
            "tvision/soutline.cpp",
            "tvision/sparamte.cpp",
            "tvision/sradiobu.cpp",
            "tvision/srescoll.cpp",
            "tvision/sscrlbar.cpp",
            "tvision/sscrolle.cpp",
            "tvision/sstatict.cpp",
            "tvision/sstatusl.cpp",
            "tvision/sstrcoll.cpp",
            "tvision/sstrlst.cpp",
            "tvision/stddlg.cpp",
            "tvision/strmstat.cpp",
            "tvision/svalid.cpp",
            "tvision/sview.cpp",
            "tvision/swindow.cpp",
            "tvision/syserr.cpp",
            "tvision/tapplica.cpp",
            "tvision/tbkgrnd.cpp",
            "tvision/tbutton.cpp",
            "tvision/tchdrdlg.cpp",
            "tvision/tcheckbo.cpp",
            "tvision/tclipbrd.cpp",
            "tvision/tcluster.cpp",
            "tvision/tcmdset.cpp",
            "tvision/tcollect.cpp",
            "tvision/tdesktop.cpp",
            "tvision/tdialog.cpp",
            "tvision/tdircoll.cpp",
            "tvision/tdirlist.cpp",
            "tvision/teditor1.cpp",
            "tvision/teditor2.cpp",
            "tvision/teditwnd.cpp",
            "tvision/tevent.cpp",
            "tvision/textview.cpp",
            "tvision/tfildlg.cpp",
            "tvision/tfilecol.cpp",
            "tvision/tfiledtr.cpp",
            "tvision/tfillist.cpp",
            "tvision/tframe.cpp",
            "tvision/tgrmv.cpp",
            "tvision/tgroup.cpp",
            "tvision/thistory.cpp",
            "tvision/thistwin.cpp",
            "tvision/thstview.cpp",
            "tvision/tindictr.cpp",
            "tvision/tinputli.cpp",
            "tvision/tkey.cpp",
            "tvision/tlabel.cpp",
            "tvision/tlistbox.cpp",
            "tvision/tlstview.cpp",
            "tvision/tmemo.cpp",
            "tvision/tmenubar.cpp",
            "tvision/tmenubox.cpp",
            "tvision/tmenupop.cpp",
            "tvision/tmnuview.cpp",
            "tvision/tmouse.cpp",
            "tvision/tmulchkb.cpp",
            "tvision/tobject.cpp",
            "tvision/tobjstrm.cpp",
            "tvision/toutline.cpp",
            "tvision/tparamte.cpp",
            "tvision/tprogram.cpp",
            "tvision/tradiobu.cpp",
            "tvision/trescoll.cpp",
            "tvision/tresfile.cpp",
            "tvision/tscreen.cpp",
            "tvision/tscrlbar.cpp",
            "tvision/tscrolle.cpp",
            "tvision/tsortcol.cpp",
            "tvision/tstatict.cpp",
            "tvision/tstatusl.cpp",
            "tvision/tstrcoll.cpp",
            "tvision/tstrlist.cpp",
            "tvision/tstrview.cpp",
            "tvision/tsurface.cpp",
            "tvision/ttimerqu.cpp",
            "tvision/ttprvlns.cpp",
            "tvision/tvalidat.cpp",
            "tvision/tvcursor.cpp",
            "tvision/tvexposd.cpp",
            "tvision/tview.cpp",
            "tvision/tvtext1.cpp",
            "tvision/tvtext2.cpp",
            "tvision/tvwrite.cpp",
            "tvision/twindow.cpp",
        },
    });
    exe.linkLibCpp();
    exe.addIncludePath(b.path("include"));
    exe.addIncludePath(b.path("include/tvision"));
    exe.addIncludePath(b.path("include/tvision/compat/borland"));

    zcc.createStep(b, "cdb", targets.toOwnedSlice() catch @panic("OOM"));
}
